{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/ABT/", "company_name": "BEN TRE AQUAPRODUCT IMPORT AND EXPORT JSC", "ticker_symbol": "ABT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Banking", "url": "http://stock.vietnammarkets.com/banking/ACB/", "company_name": "ASIA COMMERCIAL BANK", "ticker_symbol": "ACB", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/ACL/", "company_name": "CUU LONG FISH JOINT STOCK COMPANY", "ticker_symbol": "ACL", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/AGF/", "company_name": "AN GIANG FISHERIES IMPORT & EXPORT JOINT STOCK COMPANY", "ticker_symbol": "AGF", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/ALP/", "company_name": "ALPHANAM JOINT STOCK COMPANY", "ticker_symbol": "ALP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/ALT/", "company_name": "TAN BINH CULTURE CO.", "ticker_symbol": "ALT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/ANV/", "company_name": "NAM VIET JOINT STOCK COMPANY", "ticker_symbol": "ANV", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/BBC/", "company_name": "BIBICA CORPORATION", "ticker_symbol": "BBC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/BBS/", "company_name": "BUT SON CEMENT PACKING JOINT STOCK COMPANY", "ticker_symbol": "BBS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Personal equipment", "url": "http://stock.vietnammarkets.com/personal-equipment/BBT/", "company_name": "BACH TUYET COTTON JOINT STOCK COMPANY", "ticker_symbol": "BBT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/BCC/", "company_name": "BIM SON CEMENT JOINT STOCK COMPANY", "ticker_symbol": "BCC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/BHS/", "company_name": "BEN HOA SUGAR JOINT STOCK COMPANY", "ticker_symbol": "BHS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/BHV/", "company_name": "VIGLACERA BA HIEN JOINT - STOCK COMPANY", "ticker_symbol": "BHV", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Mining", "url": "http://stock.vietnammarkets.com/mining/BMC/", "company_name": "BINH DINH MINERALS JOINT STOCK COMPANY", "ticker_symbol": "BMC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Nonlife insurance", "url": "http://stock.vietnammarkets.com/nonlife-insurance/BMI/", "company_name": "BAO MINH INSURANCE CORPORATION", "ticker_symbol": "BMI", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/BMP/", "company_name": "BINH MINH PLASTICS JOINT STOCK COMPANY", "ticker_symbol": "BMP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/BPC/", "company_name": "BIM SON PACKING JOINT STOCK COMPANY", "ticker_symbol": "BPC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/BT6/", "company_name": "620-CHAU THOI CONCRETE JOINT STOCK COMPANY", "ticker_symbol": "BT6", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Mechanical engineering", "url": "http://stock.vietnammarkets.com/mechanical-engineering/BTC/", "company_name": "BINH TRIEU MACHINERY AND CONSTRUCTION JOINT STOCK COMPANY", "ticker_symbol": "BTC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/BTH/", "company_name": "HANOI TRANSFORMER & ELECTRIC MATERIALS MANUFACTURING JOINT STOCK COMPANY", "ticker_symbol": "BTH", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/BTS/", "company_name": "BUT SON CEMENT JOINT STOCK COMPANY", "ticker_symbol": "BTS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Financial services", "url": "http://stock.vietnammarkets.com/financial-services/BVS/", "company_name": "BAOVIET SECURITIES COMPANY", "ticker_symbol": "BVS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/C92/", "company_name": "ENGINEERING CONSTRUCTION JOINT STOCK COMPANY NO. 492", "ticker_symbol": "C92", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/CAN/", "company_name": "HA LONG CANNED FOOD JOINT STOCK COMPANY", "ticker_symbol": "CAN", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/CAP/", "company_name": "YEN BAI FOREST AGRICULTURAL AND FOODSTUFFS JOINT STOCK COMPANY", "ticker_symbol": "CAP", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/CDC/", "company_name": "CHUONG DUONG ASSEMBLY CONSTRUCTION & INVESTMENT JOINT STOCK COMPANY", "ticker_symbol": "CDC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/CIC/", "company_name": "COTEC INVESTMENT AND CONSTRUCTION JOINT STOCK COMPANY", "ticker_symbol": "CIC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/CID/", "company_name": "CONSTRUCTION AND INFRASTRUCTURE DEVELOPMENT JOINT STOCK CORPORATION", "ticker_symbol": "CID", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/CII/", "company_name": "HO CHI MINH CITY INFRASTRUCTURE INVESTMENT JOINT STOCK COMPANY", "ticker_symbol": "CII", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Mechanical engineering", "url": "http://stock.vietnammarkets.com/mechanical-engineering/CJC/", "company_name": "CENTRAL AREA ELECTRICAL MECHANICAL JOINT STOCK COMPANY", "ticker_symbol": "CJC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/CLC/", "company_name": "CAT LOI JOINT STOCK COMPANY", "ticker_symbol": "CLC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Mechanical engineering", "url": "http://stock.vietnammarkets.com/mechanical-engineering/CMC/", "company_name": "CONSTRUCTION AND MECHANICAL JOINT STOCK COMPANY No 1.", "ticker_symbol": "CMC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Oil and gas production", "url": "http://stock.vietnammarkets.com/oil-and-gas-production/COM/", "company_name": "MATERIALS - PETROLIUM JOINT STOCK COMPANY", "ticker_symbol": "COM", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Mechanical engineering", "url": "http://stock.vietnammarkets.com/mechanical-engineering/CTB/", "company_name": "HAI DUONG PUMP MANUFACTURING JOINT STOCK COMPANY", "ticker_symbol": "CTB", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/CTN/", "company_name": "UNDERGROUND WORKS CONSTRUCTION JOINT STOCK COMPANY", "ticker_symbol": "CTN", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/CYC/", "company_name": "CHANG YIH CERAMIC JOINT STOCK COMPANY", "ticker_symbol": "CYC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/DAC/", "company_name": "DONG ANH CERAMIC JOINT STOCK COMPANY", "ticker_symbol": "DAC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Communication", "url": "http://stock.vietnammarkets.com/communication/DAE/", "company_name": "EDUCATIONAL BOOK JOINT STOCK COMPANY IN DA NANG CITY", "ticker_symbol": "DAE", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/DCC/", "company_name": "DESCON CONSTRUCTION CORPORATION", "ticker_symbol": "DCC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/DCS/", "company_name": "DAI CHAU JOINT STOCK COMPANY", "ticker_symbol": "DCS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/DCT/", "company_name": "DONG NAI ROOFSHEET & CONSTRUCTION MATERIAL JSC", "ticker_symbol": "DCT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/DHA/", "company_name": "HOA AN STONE EXPLOITATION JOINT STOCK COMPANY", "ticker_symbol": "DHA", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Pharmacy and biotech", "url": "http://stock.vietnammarkets.com/pharmacy-and-biotech/DHG/", "company_name": "HAU GIANG PHARMACEUTICAL JSC", "ticker_symbol": "DHG", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Communication", "url": "http://stock.vietnammarkets.com/communication/DHI/", "company_name": "DIEN HONG PRINTING JOINT STOCK COMPANY", "ticker_symbol": "DHI", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/DIC/", "company_name": "DIC INVESTMENT AND TRADING JSC", "ticker_symbol": "DIC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Pharmacy and biotech", "url": "http://stock.vietnammarkets.com/pharmacy-and-biotech/DMC/", "company_name": "DOMESCO MEDICAL IMPORT EXPORT JSC", "ticker_symbol": "DMC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/DNP/", "company_name": "DONG NAI PLASTIC CONSTRUCTION JSC", "ticker_symbol": "DNP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/DPC/", "company_name": "DA NANG PLASTIC JOINT STOCK COMPANY", "ticker_symbol": "DPC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/DPM/", "company_name": "PETROVIETNAM FERTILIZER AND CHEMICALS COMPANY", "ticker_symbol": "DPM", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/DPR/", "company_name": "Dong Phu Rubber Joint Stock Company", "ticker_symbol": "DPR", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/DRC/", "company_name": "DANANG RUBBER JOINT STOCK COMPANY", "ticker_symbol": "DRC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/DST/", "company_name": "NAM DINH EDUCATIONAL BOOK AND EQUIPMENT JOINT STOCK COMPANY", "ticker_symbol": "DST", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/DTC/", "company_name": "VIGLACERA DONG TRIEU JOINT STOCK COMPANY", "ticker_symbol": "DTC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/DTT/", "company_name": "DO THANH TECHNOLOGY CORPORATION", "ticker_symbol": "DTT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/DXP/", "company_name": "DOAN XA PORT JOINT STOCK COMPANY", "ticker_symbol": "DXP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Communication", "url": "http://stock.vietnammarkets.com/communication/EBS/", "company_name": "EDUCATIONAL BOOK JOINT STOCK COMPANY", "ticker_symbol": "EBS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/FMC/", "company_name": "SAO TA FOODS JOINT STOCK COMPANY", "ticker_symbol": "FMC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/FPC/", "company_name": "FULL POWER JOINT STOCK COMPANY", "ticker_symbol": "FPC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/FPT/", "company_name": "THE CORPORATION FOR FINANCING AND PROMOTING TECHNOLOGY", "ticker_symbol": "FPT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Paper and wood products", "url": "http://stock.vietnammarkets.com/paper-and-wood-products/GHA/", "company_name": "HAI AU PAPER JOINT STOCK COMPANY", "ticker_symbol": "GHA", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Personal equipment", "url": "http://stock.vietnammarkets.com/personal-equipment/GIL/", "company_name": "BINH THANH TRADING JOINT STOCK COMPANY", "ticker_symbol": "GIL", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Personal equipment", "url": "http://stock.vietnammarkets.com/personal-equipment/GMC/", "company_name": "SAIGON GARMENT MANUFACTURING TRADE JOINT STOCK COMPANY", "ticker_symbol": "GMC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/GMD/", "company_name": "GENERAL FORWARDING AND AGENCY CORP.", "ticker_symbol": "GMD", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/GTA/", "company_name": "THUAN AN WOOD PROCESSING JOINT STOCK COMPANY", "ticker_symbol": "GTA", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/HAI/", "company_name": "HAI AGROCHEM JOINT STOCK COMPANY", "ticker_symbol": "HAI", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Paper and wood products", "url": "http://stock.vietnammarkets.com/paper-and-wood-products/HAP/", "company_name": "HAI PHONG PAPER JOINT STOCK COMPANY", "ticker_symbol": "HAP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/HAS/", "company_name": "HANOI POST CONSTRUCTION AND INSTALLATION CO.", "ticker_symbol": "HAS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Automobile and parts", "url": "http://stock.vietnammarkets.com/automobile-and-parts/HAX/", "company_name": "HANG XANH MOTORS SERVICE JOINT STOCK COMPANY", "ticker_symbol": "HAX", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/HBC/", "company_name": "HOA BINH CONSTRUCTION AND REAL ESTATE CORPORATION", "ticker_symbol": "HBC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/HBD/", "company_name": "BINH DUONG PP PACK MAKING JOINT STOCK COMPANY", "ticker_symbol": "HBD", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/HCC/", "company_name": "HOA CAM CONCRETE JOINT STOCK COMPANY", "ticker_symbol": "HCC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/HCT/", "company_name": "HAIPHONG CEMENT TRANSPORT JOINT STOCK COMPANY", "ticker_symbol": "HCT", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/HEV/", "company_name": "HIGHER EDUCATIONAL AND VOCATIONAL BOOK JOINT STOCK COMPANY", "ticker_symbol": "HEV", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/HHC/", "company_name": "HAI HA CONFECTIONERY JOINT STOCK COMPANY", "ticker_symbol": "HHC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/HJS/", "company_name": "NAM MU HYDROPOWER JOINT STOCK COMPANY", "ticker_symbol": "HJS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/HLY/", "company_name": "HA LONG NO. 1 VIGLACERA JOINT STOCK COMPANY", "ticker_symbol": "HLY", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Industrial metals", "url": "http://stock.vietnammarkets.com/industrial-metals/HMC/", "company_name": "HOCHIMINH CITY METAL CORPORATION", "ticker_symbol": "HMC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/HNM/", "company_name": "HANOIMILK JOINT STOCK COMPANY", "ticker_symbol": "HNM", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Financial services", "url": "http://stock.vietnammarkets.com/financial-services/HPC/", "company_name": "HAI PHONG SECURITIES JOINT STOCK COMPANY", "ticker_symbol": "HPC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/HPG/", "company_name": "HOA PHAT GROUP", "ticker_symbol": "HPG", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/HPS/", "company_name": "HOA PHAT  CONSTRUCTION STONE JOINT STOCK COMPANY", "ticker_symbol": "HPS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/HRC/", "company_name": "HOA BINH RUBBER JOINT STOCK COMPANY", "ticker_symbol": "HRC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Tourism and entertainment", "url": "http://stock.vietnammarkets.com/tourism-and-entertainment/HSC/", "company_name": "HACINCO JOINT STOCK COMPANY", "ticker_symbol": "HSC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/HSI/", "company_name": "GENERAL MATERIALS BIOCHEMISTRY FERTILIZER JOINT STOCK COMPANY", "ticker_symbol": "HSI", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/HT1/", "company_name": "HA TIEN 1 CEMENT JOINT STOCK COMPANY", "ticker_symbol": "HT1", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Communication", "url": "http://stock.vietnammarkets.com/communication/HTP/", "company_name": "HOAPHAT TEXTBOOK PRINTING JOINT STOCK COMPANY", "ticker_symbol": "HTP", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/HTV/", "company_name": "HA TIEN TRANSPORT JOINT STOCK COMPANY", "ticker_symbol": "HTV", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/ICF/", "company_name": "INVESTMENT COMMERCE FISHERIES CORPORATION", "ticker_symbol": "ICF", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/IFS/", "company_name": "INTERFOOD SHAREHOLDING CO.", "ticker_symbol": "IFS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Paper and wood products", "url": "http://stock.vietnammarkets.com/paper-and-wood-products/ILC/", "company_name": "INTERNATIONAL LABOR AND SERVICES JOINT STOCK COMPANY", "ticker_symbol": "ILC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Pharmacy and biotech", "url": "http://stock.vietnammarkets.com/pharmacy-and-biotech/IMP/", "company_name": "IMEXPHARM PHARMACEUTICAL JOINT STOCK COMPANY", "ticker_symbol": "IMP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Real estate", "url": "http://stock.vietnammarkets.com/real-estate/ITA/", "company_name": "TAN TAO INDUSTRIAL PARK CORPORATION", "ticker_symbol": "ITA", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/KBC/", "company_name": "KINH BAC CITY DEVELOPMENT SHAREHOLDING CORPORATION", "ticker_symbol": "KBC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/KDC/", "company_name": "KINH DO CORPORATION", "ticker_symbol": "KDC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Real estate", "url": "http://stock.vietnammarkets.com/real-estate/KHA/", "company_name": "KHANH HOI IMPORT-EXPORT JOINT STOCK COMPANY", "ticker_symbol": "KHA", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/KHP/", "company_name": "KHANH HOA POWER JOINT STOCK COMPANY", "ticker_symbol": "KHP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/KMF/", "company_name": "MIRAE FIBER JOINT STOCK COMPANY", "ticker_symbol": "KMF", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/L10/", "company_name": "LILAMA 10 JOINT STOCK COMPANY", "ticker_symbol": "L10", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/LAF/", "company_name": "LONG AN FOOD PROCESSING & EXPORT JOINT STOCK COMPANY", "ticker_symbol": "LAF", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/LBM/", "company_name": "LAM DONG BUILDING MATERIALS JOINT STOCK COMPANY", "ticker_symbol": "LBM", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/LGC/", "company_name": "LU GIA MECHANICAL ELECTRIC JOINT STOCK COMPANY (LUGIACO)", "ticker_symbol": "LGC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/LTC/", "company_name": "LOW CURRENT - TELECOM JOINT STOCK COMPANY", "ticker_symbol": "LTC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/MCO/", "company_name": "INVESTMENT AND CONSTRUCTION  JOINT STOCK COMPANY NO1", "ticker_symbol": "MCO", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/MCP/", "company_name": "MY CHAU PRINTING AND PACKAGING HOLDINGS CO.", "ticker_symbol": "MCP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Mining", "url": "http://stock.vietnammarkets.com/mining/MCV/", "company_name": "CAVICO VIETNAM MINING AND CONSTRUCTION JOINT STOCK COMPANY", "ticker_symbol": "MCV", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/MEC/", "company_name": "SONG DA MECHANICAL ASSEMBLING JOINT STOCK COMPANY", "ticker_symbol": "MEC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/MHC/", "company_name": "HANOI MARITIME HOLDING CO.", "ticker_symbol": "MHC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/MIC/", "company_name": "QUANG NAM MINERAL INDUSTRY JOINT STOCK COMPANY", "ticker_symbol": "MIC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/MPC/", "company_name": "MINH PHU SEAFOOD JOINT STOCK COMPANY", "ticker_symbol": "MPC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/NAV/", "company_name": "NAM VIET JOINT STOCK COMPANY", "ticker_symbol": "NAV", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Mining", "url": "http://stock.vietnammarkets.com/mining/NBC/", "company_name": "VINACOMIN \u00e2\u20ac\u201c NUI BEO COAL JOINT STOCK COMPANY", "ticker_symbol": "NBC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/NHC/", "company_name": "NHI HIEP BRICK-TILE JOINT STOCK COMPANY", "ticker_symbol": "NHC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/NKD/", "company_name": "NORTH KINH DO FOOD JOINT STOCK COMPANY", "ticker_symbol": "NKD", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/NLC/", "company_name": "NALOI HYDROPOWER JOINT STOCK COMPANY", "ticker_symbol": "NLC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Personal equipment", "url": "http://stock.vietnammarkets.com/personal-equipment/NPS/", "company_name": "PHU THINH - NHA BE GARMENT JOINT STOCK COMPANY", "ticker_symbol": "NPS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/NSC/", "company_name": "NATIONAL SEED JOINT STOCK COMPANY", "ticker_symbol": "NSC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Tobacco", "url": "http://stock.vietnammarkets.com/tobacco/NST/", "company_name": "NGAN SON JOINT STOCK COMPANY", "ticker_symbol": "NST", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/NTL/", "company_name": "TU LIEN URBAN DEVELOPMENT JOINT STOCK COMPANY", "ticker_symbol": "NTL", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/NTP/", "company_name": "TIEN PHONG PLASTIC JOINT STOCK COMPANY", "ticker_symbol": "NTP", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Electric and electronics equipment", "url": "http://stock.vietnammarkets.com/electric-and-electronics-equipment/PAC/", "company_name": "DRY CELL AND STORAGE BATTERY JOINT STOCK COMPANY", "ticker_symbol": "PAC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Supporting services", "url": "http://stock.vietnammarkets.com/supporting-services/PAN/", "company_name": "PAN PACIFIC CORPORATION", "ticker_symbol": "PAN", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Oil and gas equipment, services and distribution", "url": "http://stock.vietnammarkets.com/oil-and-gas-equipment-services-and-distribution/PET/", "company_name": "PETROVIETNAM TOURISM AND SERVICES JOINT STOCK COMPANY", "ticker_symbol": "PET", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Oil and gas equipment, services and distribution", "url": "http://stock.vietnammarkets.com/oil-and-gas-equipment-services-and-distribution/PGC/", "company_name": "GAS PETROLIMEX JOINT STOCK COMPANY", "ticker_symbol": "PGC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/PGS/", "company_name": "PETROVIETNAM SOUTHERN GAS JOINT STOCK COMPANY", "ticker_symbol": "PGS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/PJC/", "company_name": "PETROLIMEX HANOI TRANSPORTATION AND TRADING JOINT STOCK COMPANY.", "ticker_symbol": "PJC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/PJT/", "company_name": "PETROLIMEX JOINT STOCK TANKER CO.", "ticker_symbol": "PJT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/PLC/", "company_name": "PETROLIMEX PETROCHEMICAL JOINT STOCK COMPANY", "ticker_symbol": "PLC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Oil and gas equipment, services and distribution", "url": "http://stock.vietnammarkets.com/oil-and-gas-equipment-services-and-distribution/PMS/", "company_name": "PETROLEUM MECHANICAL JOINT STOCK COMPANY", "ticker_symbol": "PMS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/PNC/", "company_name": "PHUONG NAM CULTURAL JOINT STOCK COMPANY", "ticker_symbol": "PNC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Hardware and parts", "url": "http://stock.vietnammarkets.com/hardware-and-parts/POT/", "company_name": "POST AND TELECOMMUNICATION EQUIPMENT FACTORY", "ticker_symbol": "POT", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/PPC/", "company_name": "PHA LAI THERMAL POWER JOINT-STOCK CO.", "ticker_symbol": "PPC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/PPG/", "company_name": "PHU PHONG CORPORATION", "ticker_symbol": "PPG", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Close investment fund", "url": "http://stock.vietnammarkets.com/close-investment-fund/PRUBF1/", "company_name": "PRUDENTIAL BALANCED FUND", "ticker_symbol": "PRUBF1", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/PSC/", "company_name": "PETROLIMEX SAIGON TRANSPORTATION AND SERVICE JOINT STOCK COMPANY.", "ticker_symbol": "PSC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/PTC/", "company_name": "POST AND TELECOMMUNICATION INVESTMENT AND CONSTRUCTION JOINT STOCK COMPANY", "ticker_symbol": "PTC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/PTS/", "company_name": "HAIPHONG PETROLIMEX TRANSPORTATION AND SERVICES JOINT STOCK COMPANY", "ticker_symbol": "PTS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/PVC/", "company_name": "PETROVIETNAM DRILLING MUD JOINT STOCK COMPANY", "ticker_symbol": "PVC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Oil and gas equipment, services and distribution", "url": "http://stock.vietnammarkets.com/oil-and-gas-equipment-services-and-distribution/PVD/", "company_name": "PETROVIETNAM DRILLING & WELL SERVICES JS CO", "ticker_symbol": "PVD", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/PVE/", "company_name": "PETROVIETNAM INVESTMENT CONSULTANCY AND ENGINEERING JOINT STOCK COMPANY", "ticker_symbol": "PVE", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Nonlife insurance", "url": "http://stock.vietnammarkets.com/nonlife-insurance/PVI/", "company_name": "PETROVIETNAM INSURANCE JOINT STOCK CORPORATION", "ticker_symbol": "PVI", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Oil and gas equipment, services and distribution", "url": "http://stock.vietnammarkets.com/oil-and-gas-equipment-services-and-distribution/PVS/", "company_name": "PETROLEUM TECHNICAL SERVICES CORPORATION", "ticker_symbol": "PVS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/PVT/", "company_name": "PETROVIETNAM TRANSPORTATION CORPORATION", "ticker_symbol": "PVT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Household equipment", "url": "http://stock.vietnammarkets.com/household-equipment/RAL/", "company_name": "RANG DONG LIGHT SOURCES & VACUUM FLASK JSC", "ticker_symbol": "RAL", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Real estate", "url": "http://stock.vietnammarkets.com/real-estate/RCL/", "company_name": "CHOLON REAL ESTATE JOINT STOCK COMPANY", "ticker_symbol": "RCL", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/REE/", "company_name": "REFRIGERATION & ELECTRICAL ENGINEERING CORP.", "ticker_symbol": "REE", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/RHC/", "company_name": "RY NINH II ELECTRIC JOINT STOCK COMPANY", "ticker_symbol": "RHC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Tourism and entertainment", "url": "http://stock.vietnammarkets.com/tourism-and-entertainment/RIC/", "company_name": "ROYAL INTERNATIONAL CORPORATION", "ticker_symbol": "RIC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/S55/", "company_name": "SONG DA 505 JOINT STOCK COMPANY", "ticker_symbol": "S55", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/S64/", "company_name": "SONG DA 6.04 JOINT STOCK COMPANY", "ticker_symbol": "S64", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/S91/", "company_name": "SONG DA 9.01 JOINT STOCK COMPANY", "ticker_symbol": "S91", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/S99/", "company_name": "SONG DA 909 JOINT STOCK COMPANY", "ticker_symbol": "S99", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/SAF/", "company_name": "SAFOCO FOODSTUFF JOINT STOCK COMPANY", "ticker_symbol": "SAF", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electric and electronics equipment", "url": "http://stock.vietnammarkets.com/electric-and-electronics-equipment/SAM/", "company_name": "SAIGON CABLES AND TELECOMMUNICATIONS MATERIAL JOINT STOCK COMPANY", "ticker_symbol": "SAM", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Communication", "url": "http://stock.vietnammarkets.com/communication/SAP/", "company_name": "TEXTBOOK PRINTING JOINT STOCK COMPANY IN HO CHI MINH CITY", "ticker_symbol": "SAP", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Household equipment", "url": "http://stock.vietnammarkets.com/household-equipment/SAV/", "company_name": "SAVIMEX ECONOMIC COOPERATION AND IMPORT-EXPORT JOINT STOCK COMPANY", "ticker_symbol": "SAV", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SCC/", "company_name": "SONGDA CEMENT JOINT STOCK COMPANY", "ticker_symbol": "SCC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Drinks", "url": "http://stock.vietnammarkets.com/drinks/SCD/", "company_name": "CHUONG DUONG BEVERAGES CO.", "ticker_symbol": "SCD", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SCJ/", "company_name": "SAI SON CEMENT JOINT STOCK COMPANY", "ticker_symbol": "SCJ", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/SD2/", "company_name": "SONG DA NO. 2 JOINT STOCK COMPANY", "ticker_symbol": "SD2", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SD3/", "company_name": "SONG DA 3 JOINT STOCK COMPANY", "ticker_symbol": "SD3", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SD5/", "company_name": "SONG DA NO. 5 JOINT STOCK COMPANY", "ticker_symbol": "SD5", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SD6/", "company_name": "SONG DA N0. 6 JOINT STOCK COMPANY", "ticker_symbol": "SD6", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SD7/", "company_name": "SONGDA 7 JOINT STOCK COMPANY", "ticker_symbol": "SD7", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SD9/", "company_name": "SONG DA NO. 9 JOINT STOCK COMPANY", "ticker_symbol": "SD9", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Supporting services", "url": "http://stock.vietnammarkets.com/supporting-services/SDA/", "company_name": "SONG DA INTERNATIONAL MANPOWER SUPPLY AND TRADING JOINT STOCK COMPANY", "ticker_symbol": "SDA", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SDC/", "company_name": "SONG DA CONSULTING JOINT STOCK COMPANY", "ticker_symbol": "SDC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/SDJ/", "company_name": "SONG DA NO. 25 JOINT STOCK COMPANY", "ticker_symbol": "SDJ", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SDN/", "company_name": "DONG NAI PAINT CORPORATION", "ticker_symbol": "SDN", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SDT/", "company_name": "SONG DA N0 10. JOINT STOCK COMPANY", "ticker_symbol": "SDT", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SDY/", "company_name": "SONG DA YALY CEMENT JOINT STOCK COMPANY", "ticker_symbol": "SDY", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/SFC/", "company_name": "SAIGON FUEL JOINT STOCK COMPANY", "ticker_symbol": "SFC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/SFI/", "company_name": "SEA AND AIR FREIGHT INTERNATIONAL", "ticker_symbol": "SFI", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Supporting services", "url": "http://stock.vietnammarkets.com/supporting-services/SFN/", "company_name": "SAIGON FISHING NET JOINT STOCK COMPANY", "ticker_symbol": "SFN", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/SGC/", "company_name": "SAGIANG IMPORT AND EXPORT CORPORATION", "ticker_symbol": "SGC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Communication", "url": "http://stock.vietnammarkets.com/communication/SGD/", "company_name": "EDUCATIONAL BOOK JOINT STOCK COMPANY IN HO CHI MINH CITY", "ticker_symbol": "SGD", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Tourism and entertainment", "url": "http://stock.vietnammarkets.com/tourism-and-entertainment/SGH/", "company_name": "SAIGON HOTEL JOINT STOCK COMPANY", "ticker_symbol": "SGH", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/SHC/", "company_name": "SAI GON MARITIME JOINT STOCK COMPANY", "ticker_symbol": "SHC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Real estate", "url": "http://stock.vietnammarkets.com/real-estate/SIC/", "company_name": "SONG DA INVESTMENT - DEVELOPMENT JOINT STOCK COMPANY", "ticker_symbol": "SIC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/SJ1/", "company_name": "SEAFOOD JOINT STOCK COMPANY NO 1", "ticker_symbol": "SJ1", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/SJC/", "company_name": "SONG DA 1.01 JOINT STOCK COMPANY", "ticker_symbol": "SJC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/SJD/", "company_name": "CAN DON HYDROELECTRIC JOINT STOCKS CO.", "ticker_symbol": "SJD", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SJE/", "company_name": "SONG DA N011 JOINT STOCK COMPANY", "ticker_symbol": "SJE", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Real estate", "url": "http://stock.vietnammarkets.com/real-estate/SJS/", "company_name": "SONG DA URBAN & INDUSTRIAL ZONE INVESTMENT AND DEVELOPMENT JOINT STOCK COMPANY", "ticker_symbol": "SJS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Industrial metals", "url": "http://stock.vietnammarkets.com/industrial-metals/SMC/", "company_name": "SMC TRADING - INVESTMENT JOINT STOCK COMPANY", "ticker_symbol": "SMC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SNG/", "company_name": "SONG DA N0. 10.1 JOINT STOCK COMPANY", "ticker_symbol": "SNG", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/SSC/", "company_name": "SOUTHERN SEED JOINT STOCK COMPANY", "ticker_symbol": "SSC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Financial services", "url": "http://stock.vietnammarkets.com/financial-services/SSI/", "company_name": "SAIGON SECURITIES INC.", "ticker_symbol": "SSI", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/SSS/", "company_name": "SONG DA NO. 6.06 JOINT STOCK COMPANY", "ticker_symbol": "SSS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/ST8/", "company_name": "SIEU THANH JOINT STOCK CORPORATION", "ticker_symbol": "ST8", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Banking", "url": "http://stock.vietnammarkets.com/banking/STB/", "company_name": "SAIGON THUONG TIN COMMERCIAL JOINT STOCK BANK", "ticker_symbol": "STB", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/STC/", "company_name": "BOOK AND EDUCATIONAL EQUIPMENT JOINT STOCK COMPANY", "ticker_symbol": "STC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/STP/", "company_name": "SONG DA INDUSTRY TRADE JOINT STOCK COMPANY", "ticker_symbol": "STP", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/SVC/", "company_name": "SAIGON GENERAL SERVICE CORPORATION", "ticker_symbol": "SVC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/TAC/", "company_name": "TUONG AN VEGETABLE OIL JOINT STOCK COMPANY", "ticker_symbol": "TAC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/TBC/", "company_name": "THAC BA HYDROPOWER JOINT STOCK COMPANY", "ticker_symbol": "TBC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/TCR/", "company_name": "TAICERA ENTERPRISE COMPANY", "ticker_symbol": "TCR", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/TCT/", "company_name": "TAY NINH CABLE CAR TOUR CO.", "ticker_symbol": "TCT", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Real estate", "url": "http://stock.vietnammarkets.com/real-estate/TDH/", "company_name": "THU DUC HOUSING DEVELOPMENT CORPORATION", "ticker_symbol": "TDH", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/TJC/", "company_name": "TRANSPORTATION AND TRADING SERVICES JOINT STOCK COMPANY", "ticker_symbol": "TJC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Industrial metals", "url": "http://stock.vietnammarkets.com/industrial-metals/TKU/", "company_name": "TUNG KUANG INDUSTRIAL JOINT STOCK COMPANY", "ticker_symbol": "TKU", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Electric and electronics equipment", "url": "http://stock.vietnammarkets.com/electric-and-electronics-equipment/TLC/", "company_name": "THANG LONG TELECOM JOINT STOCK COMPANY", "ticker_symbol": "TLC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/TLT/", "company_name": "VIGLACERA THANGLONG CERAMIC TILES JOINT STOCK COMPANY", "ticker_symbol": "TLT", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/TMC/", "company_name": "THU DUC TRADING AND IMPORT EXPORT JOINT STOCK COMPANY", "ticker_symbol": "TMC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/TMS/", "company_name": "TRANSFORWARDING & WAREHOUSING JOINT STOCK COMPANY", "ticker_symbol": "TMS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Distribution", "url": "http://stock.vietnammarkets.com/distribution/TNA/", "company_name": "THIEN NAM IMPORT AND EXPORT JOINT STOCK COMPANY", "ticker_symbol": "TNA", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/TNC/", "company_name": "THONG NHAT RUBBER JOINT STOCK COMPANY", "ticker_symbol": "TNC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/TNG/", "company_name": "TNG INVESTMENT AND TRADING JOINT STOCK COMPANY", "ticker_symbol": "TNG", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/TPC/", "company_name": "TAN DAI HUNG PLASTIC JOINT STOCK COMPANY", "ticker_symbol": "TPC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Communication", "url": "http://stock.vietnammarkets.com/communication/TPH/", "company_name": "HANOI TEXTBOOKS PRINTING JOINT STOCK COMPANY", "ticker_symbol": "TPH", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Chemicals", "url": "http://stock.vietnammarkets.com/chemicals/TRC/", "company_name": "TAY NINH RUBBER JOINT STOCK COMPANY", "ticker_symbol": "TRC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Drinks", "url": "http://stock.vietnammarkets.com/drinks/TRI/", "company_name": "SAIGON FOOD & BEVERAGE JOINT STOCK COMPANY", "ticker_symbol": "TRI", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/TS4/", "company_name": "SEAFOOD IMPORT-EXPORT JS CO. NO. 4", "ticker_symbol": "TS4", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/TSC/", "company_name": "TECHNO \u00e2\u20ac\u201c AGRICULTURAL SUPPLYING JOINT STOCK COMPANY", "ticker_symbol": "TSC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/TST/", "company_name": "TELECOMMUNICATION TECHNICAL SERVICE JOINT STOCK COMPANY", "ticker_symbol": "TST", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/TTC/", "company_name": "THANH THANH JOINT STOCK COMPANY", "ticker_symbol": "TTC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/TTP/", "company_name": "TAN TIEN PLASTIC PACKAGING JOINT STOCK COMPANY", "ticker_symbol": "TTP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/TXM/", "company_name": "GYPSUM AND CEMENT JOINT STOCK COMPANY", "ticker_symbol": "TXM", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Electric and electronics equipment", "url": "http://stock.vietnammarkets.com/electric-and-electronics-equipment/TYA/", "company_name": "TAYA VIETNAM ELECTRIC WIRE AND CABLE JOINT STOCK COMPANY", "ticker_symbol": "TYA", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/UIC/", "company_name": "IDICO URBAN AND HOUSE DEVELOPMENT INVESTMENT JOINT STOCK COMPANY", "ticker_symbol": "UIC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Hardware and parts", "url": "http://stock.vietnammarkets.com/hardware-and-parts/UNI/", "company_name": "VIEN LIEN JOINT - STOCK CO.", "ticker_symbol": "UNI", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electric and electronics equipment", "url": "http://stock.vietnammarkets.com/electric-and-electronics-equipment/VBH/", "company_name": "VIETTRONICS BINH HOA JOINT STOCK COMPANY", "ticker_symbol": "VBH", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/VC2/", "company_name": "VIET NAM CONSTRUCTION JOINT STOCK COMPANY NO. 2", "ticker_symbol": "VC2", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/VC3/", "company_name": "VIETNAM CONSTRUCTION JOINT STOCK COMPANY NO. 3", "ticker_symbol": "VC3", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/VCS/", "company_name": "ADVANCED COMPOUND STONE JOINT STOCK COMPANY", "ticker_symbol": "VCS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/VDL/", "company_name": "LAM DONG FOODSTUFF JOINT STOCK COMPANY", "ticker_symbol": "VDL", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/VFC/", "company_name": "VINAFCO JOINT STOCK CORPORATION", "ticker_symbol": "VFC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Close investment fund", "url": "http://stock.vietnammarkets.com/close-investment-fund/VFMVF1/", "company_name": "VIETFUND MANAGEMENT 1", "ticker_symbol": "VFMVF1", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/VFR/", "company_name": "TRANSPORT AND CHARTERING CORPORATION", "ticker_symbol": "VFR", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/VGP/", "company_name": "VEGETABLE PORT JOINT STOCK COMPANY", "ticker_symbol": "VGP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/VHC/", "company_name": "VINH HOAN JOINT STOCK COMPANY", "ticker_symbol": "VHC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Real estate", "url": "http://stock.vietnammarkets.com/real-estate/VIC/", "company_name": "VINCOM JOINT STOCK COMPANY", "ticker_symbol": "VIC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Paper and wood products", "url": "http://stock.vietnammarkets.com/paper-and-wood-products/VID/", "company_name": "VIEN DONG PAPER JOINT STOCK COMPANY", "ticker_symbol": "VID", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/VIP/", "company_name": "VIET NAM PETROLIUM TRANSPORT JOINT STOCK COMPANY", "ticker_symbol": "VIP", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Industrial metals", "url": "http://stock.vietnammarkets.com/industrial-metals/VIS/", "company_name": "VIETNAM- ITALY STEEL JOINT STOCK COMPANY", "ticker_symbol": "VIS", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/VMC/", "company_name": "MACHINERY ERECTION AND CONSTRUCTION JOINT STOCK COMPANY", "ticker_symbol": "VMC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Supporting services", "url": "http://stock.vietnammarkets.com/supporting-services/VNC/", "company_name": "VIETNAM SUPERINTENDENCE AND INSPECTION JOINT STOCK COMPANY", "ticker_symbol": "VNC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/VNE/", "company_name": "VIETNAM ELECTRICITY CONSTRUCTION JOINT-STOCK CORPORATION", "ticker_symbol": "VNE", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Food processing", "url": "http://stock.vietnammarkets.com/food-processing/VNM/", "company_name": "VIETNAM DAIRY CORPORATION", "ticker_symbol": "VNM", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Nonlife insurance", "url": "http://stock.vietnammarkets.com/nonlife-insurance/VNR/", "company_name": "VIETNAM  NATIONAL REINSURANCE CORPORATION", "ticker_symbol": "VNR", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "General industries", "url": "http://stock.vietnammarkets.com/general-industries/VPK/", "company_name": "VEGETABLE OIL PACKING JOINT STOCK COMPANY", "ticker_symbol": "VPK", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/VSC/", "company_name": "VIETNAM CONTAINER SHIPPING COMPANY", "ticker_symbol": "VSC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Electricity", "url": "http://stock.vietnammarkets.com/electricity/VSH/", "company_name": "VINH SON \u00e2\u20ac\u201c SONG HINH HYDROPOWER JOINT STOCK COMPANY", "ticker_symbol": "VSH", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Oil and gas production", "url": "http://stock.vietnammarkets.com/oil-and-gas-production/VSP/", "company_name": "VINASHIN PETROLEUM INVESTMENT AND TRANSPORT JOINT STOCK COMPANY", "ticker_symbol": "VSP", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/VTA/", "company_name": "VITALY JOINT STOCK COMPANY", "ticker_symbol": "VTA", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Entertaining equipment", "url": "http://stock.vietnammarkets.com/entertaining-equipment/VTB/", "company_name": "VIETTRONICS TANBINH JOINT STOCK COMPANY", "ticker_symbol": "VTB", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Hardware and parts", "url": "http://stock.vietnammarkets.com/hardware-and-parts/VTC/", "company_name": "VTC TELECOMMUNICATIONS JOINT STOCK COMPANY", "ticker_symbol": "VTC", "listing_bourse": "HOSE"}
{"crawled_at": "2018-01-12", "business": "Drinks", "url": "http://stock.vietnammarkets.com/drinks/VTL/", "company_name": "THANGLONG JOINT STOCK COMPANY", "ticker_symbol": "VTL", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Construction materials", "url": "http://stock.vietnammarkets.com/construction-materials/VTS/", "company_name": "VIGLACERA TU SON CERAMIC JOINT STOCK COMPANY", "ticker_symbol": "VTS", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Transportation", "url": "http://stock.vietnammarkets.com/transportation/VTV/", "company_name": "MATERIALS TRANSPORT CEMENT JOINT STOCK COMPANY", "ticker_symbol": "VTV", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Others", "url": "http://stock.vietnammarkets.com/others/XMC/", "company_name": "VINACONEX XUAN MAI CONCRETE AND CONSTRUCTION JOINT STOCK COMPANY", "ticker_symbol": "XMC", "listing_bourse": "HASTC"}
{"crawled_at": "2018-01-12", "business": "Paper and wood products", "url": "http://stock.vietnammarkets.com/paper-and-wood-products/YSC/", "company_name": "YEN SON JOINT STOCK COMPANY", "ticker_symbol": "YSC", "listing_bourse": "HASTC"}
